test: use PyProjectTOML from poetry instead of poetry-core
Otherwise tests fail with

    AttributeError: 'PyProjectTOML' object has no attribute 'file'